# Generated by Django 6.0.5 on 2026-05-26 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP Export"),
                            ("utility", "Utility CSV"),
                            ("travel", "Travel Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("failed_rows", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("activity_type", models.CharField(max_length=255)),
                ("raw_quantity", models.FloatField()),
                ("raw_unit", models.CharField(max_length=50)),
                ("normalized_quantity", models.FloatField()),
                ("normalized_unit", models.CharField(max_length=50)),
                ("estimated_co2e_kg", models.FloatField()),
                ("scope", models.CharField(max_length=20)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("suspicious_flag", models.BooleanField(default=False)),
                ("suspicious_reason", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.organization",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="emissions.dataupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("locked", "Locked"),
                            ("updated", "Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("performed_by", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emission_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="emissions.emissionrecord",
                    ),
                ),
            ],
        ),
    ]
